package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Competition;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CompetitionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COMPETITION
     *
     * @mbg.generated Mon Mar 27 17:18:45 EEST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COMPETITION
     *
     * @mbg.generated Mon Mar 27 17:18:45 EEST 2023
     */
    int insert(Competition row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COMPETITION
     *
     * @mbg.generated Mon Mar 27 17:18:45 EEST 2023
     */
    Competition selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COMPETITION
     *
     * @mbg.generated Mon Mar 27 17:18:45 EEST 2023
     */
    List<Competition> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COMPETITION
     *
     * @mbg.generated Mon Mar 27 17:18:45 EEST 2023
     */
    int updateByPrimaryKey(Competition row);
}