package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Participant;
import org.mybatis.cdi.Mapper;

@Mapper
public interface ParticipantMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PARTICIPANT
     *
     * @mbg.generated Mon Mar 27 17:18:45 EEST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PARTICIPANT
     *
     * @mbg.generated Mon Mar 27 17:18:45 EEST 2023
     */
    int insert(Participant row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PARTICIPANT
     *
     * @mbg.generated Mon Mar 27 17:18:45 EEST 2023
     */
    Participant selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PARTICIPANT
     *
     * @mbg.generated Mon Mar 27 17:18:45 EEST 2023
     */
    List<Participant> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PARTICIPANT
     *
     * @mbg.generated Mon Mar 27 17:18:45 EEST 2023
     */
    int updateByPrimaryKey(Participant row);
}