package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Sponsor;
import org.mybatis.cdi.Mapper;

@Mapper
public interface SponsorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SPONSOR
     *
     * @mbg.generated Mon Mar 27 17:18:45 EEST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SPONSOR
     *
     * @mbg.generated Mon Mar 27 17:18:45 EEST 2023
     */
    int insert(Sponsor row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SPONSOR
     *
     * @mbg.generated Mon Mar 27 17:18:45 EEST 2023
     */
    Sponsor selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SPONSOR
     *
     * @mbg.generated Mon Mar 27 17:18:45 EEST 2023
     */
    List<Sponsor> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SPONSOR
     *
     * @mbg.generated Mon Mar 27 17:18:45 EEST 2023
     */
    int updateByPrimaryKey(Sponsor row);
}