package lt.vu.mybatis.model;

public class Participant {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PARTICIPANT.ID
     *
     * @mbg.generated Mon Mar 27 17:18:45 EEST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PARTICIPANT.NAME
     *
     * @mbg.generated Mon Mar 27 17:18:45 EEST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PARTICIPANT.COMPETITION_ID
     *
     * @mbg.generated Mon Mar 27 17:18:45 EEST 2023
     */
    private Long competitionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PARTICIPANT.ID
     *
     * @return the value of PUBLIC.PARTICIPANT.ID
     *
     * @mbg.generated Mon Mar 27 17:18:45 EEST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PARTICIPANT.ID
     *
     * @param id the value for PUBLIC.PARTICIPANT.ID
     *
     * @mbg.generated Mon Mar 27 17:18:45 EEST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PARTICIPANT.NAME
     *
     * @return the value of PUBLIC.PARTICIPANT.NAME
     *
     * @mbg.generated Mon Mar 27 17:18:45 EEST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PARTICIPANT.NAME
     *
     * @param name the value for PUBLIC.PARTICIPANT.NAME
     *
     * @mbg.generated Mon Mar 27 17:18:45 EEST 2023
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PARTICIPANT.COMPETITION_ID
     *
     * @return the value of PUBLIC.PARTICIPANT.COMPETITION_ID
     *
     * @mbg.generated Mon Mar 27 17:18:45 EEST 2023
     */
    public Long getCompetitionId() {
        return competitionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PARTICIPANT.COMPETITION_ID
     *
     * @param competitionId the value for PUBLIC.PARTICIPANT.COMPETITION_ID
     *
     * @mbg.generated Mon Mar 27 17:18:45 EEST 2023
     */
    public void setCompetitionId(Long competitionId) {
        this.competitionId = competitionId;
    }
}