package lt.vu.mybatis.model;

public class Sponsor {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SPONSOR.ID
     *
     * @mbg.generated Mon Mar 27 17:18:45 EEST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SPONSOR.NAME
     *
     * @mbg.generated Mon Mar 27 17:18:45 EEST 2023
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SPONSOR.ID
     *
     * @return the value of PUBLIC.SPONSOR.ID
     *
     * @mbg.generated Mon Mar 27 17:18:45 EEST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SPONSOR.ID
     *
     * @param id the value for PUBLIC.SPONSOR.ID
     *
     * @mbg.generated Mon Mar 27 17:18:45 EEST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SPONSOR.NAME
     *
     * @return the value of PUBLIC.SPONSOR.NAME
     *
     * @mbg.generated Mon Mar 27 17:18:45 EEST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SPONSOR.NAME
     *
     * @param name the value for PUBLIC.SPONSOR.NAME
     *
     * @mbg.generated Mon Mar 27 17:18:45 EEST 2023
     */
    public void setName(String name) {
        this.name = name;
    }
}